# Generated by Django 5.0.6 on 2024-08-25 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acc_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('aadhar_num', models.CharField(max_length=12, unique=True)),
                ('mobile_num', models.CharField(default='0000000000', max_length=10)),
                ('email', models.EmailField(blank=True, default='example@example.com', max_length=254, null=True)),
                ('address', models.TextField()),
                ('account_number', models.BigIntegerField(editable=False, unique=True)),
                ('pin_num', models.CharField(max_length=256)),
                ('balance_amount', models.BigIntegerField(default=0)),
                ('acc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_home_app.acc_type')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_home_app.gender')),
            ],
        ),
    ]
