# Generated by Django 5.0.6 on 2024-08-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_home_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='otp_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
