# Generated by Django 5.0.6 on 2024-08-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_home_app', '0002_bank_otp_bank_otp_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='mobile_num',
            field=models.CharField(default='0000000000', max_length=10, unique=True),
        ),
    ]
